version: "3.0"
services:
  test:
    image: rackspace-basket
    command:
      dockerize
        -wait tcp://mongodb:27017 -wait tcp://web:8080 -timeout 10s
        bash -c "npm test"
    env_file: .env-docker
    links:
      - web
      - mongodb
  web:
    container_name: rackspace-basket
    image: rackspace-basket
    build: .
    ports:
    - "8080:8080"
    env_file: .env-docker
    volumes:
    - ./host_folder/:/apps
    depends_on:
    - mongodb
    links:
    - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
    - basket_mongodb_volume:/data/db/
    ports:
    - "27017:27017"
volumes:
  basket_mongodb_volume:

